using UnityEngine;

namespace Resources.map_assets.Selector_Scripts.SelectorMVP
{
    public class SelectorModel
    {
        private SelectorPresenter selectorPresenter;
        
        private GameObject selectedProvinceObject;
        private Province selectedProvince;
        
        private GameObject currentCountryObject;
        private Nation currentCountryNation;
        
        private float cooldownBaseValue = 0.2f;
        private float inputCooldown = 0.0f;
        private float movementTime = 0.2f;
        private bool unitSelected = false;
        
        //Properties autogenerated by unity
        public SelectorModel(SelectorPresenter selectorPresenter)
        {
            this.selectorPresenter = selectorPresenter;
        }
        
        public bool canSelectProvince(GameObject hitProvinceObject)
        {
            Province hitProvince = hitProvinceObject.GetComponent<Province>();
            Province selectedProvince = selectedProvinceObject.GetComponent<Province>();

            return hitProvinceObject != selectedProvinceObject &&
                   (hitProvinceObject.GetComponentInParent<Nation>() == CurrentCountryNation ||
                    hitProvinceObject.tag == "SeaTile" ||
                    UnitSelected && hitProvince.getNeighbours().Contains(selectedProvince));
        }

        public GameObject SelectedProvinceObject
        {
            get => selectedProvinceObject;
            set => selectedProvinceObject = value;
        }
        
        public Province SelectedProvince
        {
            get => selectedProvince;
            set => selectedProvince = value;
        }

        public GameObject CurrentCountryObject
        {
            get => currentCountryObject;
            set => currentCountryObject = value;
        }

        public Nation CurrentCountryNation
        {
            get => currentCountryNation;
            set => currentCountryNation = value;
        }

        public float CooldownBaseValue
        {
            get => cooldownBaseValue;
            set => cooldownBaseValue = value;
        }

        public float InputCooldown
        {
            get => inputCooldown;
            set => inputCooldown = value;
        }

        public float MovementTime
        {
            get => movementTime;
            set => movementTime = value;
        }

        public bool UnitSelected
        {
            get => unitSelected;
            set => unitSelected = value;
        }

    }
}